### PR TITLE
de-bashify confpath()

### PR DESCRIPTION
**Pull request by rsmarples**
Not tested, but should work better than original code due to ssh using the First parameter matched, whereas the original uses the Last paramter matched.

This allows keychain to once more to work on BSD sh.

### CODE REVIEW

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2342

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.

**Comment by rsmarples** [comment]
[[ .. ]] is not POSIX
Neither is globbing in the RHS.

As such, keychain still fails on NetBSD sh.

**Comment by rsmarples** [comment]
I'll even go further and state that calling awk just to print $2 is just bad form :)

**Pull request closed without merging**
