### PR TITLE
various cleanups

### PR DESCRIPTION
**Pull request by vapier**

### CODE REVIEW

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2754

**Comment by vapier** [comment]
this was mostly fixed in commit f44f2e2ae7a824ce27c7347f7be656b00beb7e07, but i'm not going to bother with rebasing

**Comment by danielrobbins** [comment]
Did I miss anything?

**Comment by vapier** [comment]
pull request 49 has one fix, but the current code doesn't properly quote a lot of variable expansions

**Pull request closed without merging**
